export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_ALL_ORDERS = "SET_ALL_ORDERS";
export const UPDATE_ALL_USERS = "UPDATE_ALL_USERS";
export const UPDATE_ALL_ORDERS = "UPDATE_ALL_USERS";
export const CLEAR_ALL_ADMIN_INFO = "CLEAR_ALL_ADMIN_INFO";