
export const WARNING_NOTIFICATION = "WARNING_NOTIFICATION";
export const SUCCESS_NOTIFICATION = "SUCCESS_NOTIFICATION";
export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
export const INFO_NOTIFICATION = "INFO_NOTIFICATION";
export const CLEAR_NOTIFICATION_WARNING = "CLEAR_NOTIFICATION_WARNING";
export const CLEAR_NOTIFICATION_ERROR = "CLEAR_NOTIFICATION_ERROR";
export const CLEAR_NOTIFICATION_SUCCESS = "CLEAR_NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATION_INFO = "CLEAR_NOTIFICATION_INFO";