
export const SET_PROFILE = "SET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_PROFILE_ORDERS = "SET_PROFILE_ORDERS"
export const CLEAR_ALL_PROFILE_INFO = "CLEAR_ALL_PROFILE_INFO"